FROM cljkondo/clj-kondo:latest AS BASE

LABEL "com.github.actions.name"="Clojure Lint Action"
LABEL "com.github.actions.description"="A simple GitHub Action to lint clojure files with clj-kondo and reviewdog on pull requests to improve the code review experience."
LABEL "com.github.actions.color"="purple"
LABEL "com.github.actions.icon"="search"

LABEL "repository"="https://github.com/nnichols/clojure-lint-action"
LABEL "homepage"="https://github.com/nnichols"
LABEL "maintainer"="Nick Nichols <nichols1991@gmail.com>"
LABEL "version"="v1.0.0"
